# Site settings
title: Felix Wöstmann
description: Felix Wöstmann Visitenkarte
#baseurl: "/" 

# User settings
username: Felix Wöstmann
user_description:  
user_title: Softwaredeveloper
email: kontakt@felixwoestmann.me
github_username:  felixwoestmann
instagram_username:  woestmann.felix

# Google-analytics
google-analytics:
  id: ""

exclude: ['package.json', 'src' , 'node_modules']
